#!/bin/sh

xdg=$(xdg-user-dir DESKTOP)
src='/usr/share/applications'

if ! [ -f $HOME/.desktop-items-created ]; then

  if [[ -f "/usr/share/sonar/keyboard_shortcuts.txt" ]]; then
    ln -sf /usr/share/sonar/keyboard_shortcuts.txt \
    "$xdg/keyboard_shortcuts"
  fi

  if [[ -f "/usr/share/sonar/users guide.html" ]]; then
    ln -sf /usr/share/sonar/users guide.html \
    "$xdg/users_guide"
  fi

  if [[ -f "$src/ask_for_help_online.desktop" ]]; then
    install -Dm755 $src/ask_for_help_online.desktop \
    "$xdg/ask_for_help_online.desktop"
  fi

  if [[ -f "$src/connect_to_our_mumble_server_for_help.desktop" ]]; then
    install -Dm755 $src/connect_to_our_mumble_server_for_help.desktop \
    "$xdg/connect_to_our_mumble_server_for_help.desktop"
  fi

  echo "Remove this file to have the default desktop items created on next login" > $HOME/.desktop-items-created

fi
