#!/bin/bash

## Script to set the key for mate terminal colors

palette="#1B1B1D1D1E1E:#F9F926267272:#8282B4B41414:#FDFD97971F1F:#5656C2C2D6D6:#8C8C5454FEFE:#464654545757:#CCCCCCCCC6C6:#505053535454:#FFFF59599595:#B6B6E3E35454:#FEFEEDED6C6C:#8C8CEDEDFFFF:#9E9E6F6FFEFE:#89899C9CA1A1:#F8F8F8F8F2F2"
bd_color="#FFFFFFFFFFFF"
fg_color="#A0A0A0A0A0A0"
bg_color="#1C1C1C1C1C1C"
app=set-terminal-color

gsettings set org.mate.terminal.profile:/org/mate/terminal/profiles/default/ background-color $bg_color
gsettings set org.mate.terminal.profile:/org/mate/terminal/profiles/default/ foreground-color $fg_color
gsettings set org.mate.terminal.profile:/org/mate/terminal/profiles/default/ bold-color $bd_color
gsettings set org.mate.terminal.profile:/org/mate/terminal/profiles/default/ palette $palette

gsettings set org.mate.terminal.profile:/org/mate/terminal/profiles/default/ use-theme-colors false
gsettings set org.mate.terminal.profile:/org/mate/terminal/profiles/default/ bold-color-same-as-fg false

#Remove the .desktop entry in HOME user folder

rm $HOME/.config/autostart/$app.desktop

