#!/bin/sh
# fbsetbg -l # sets the last background set, very useful and recommended.

# In the below commands the ampersand symbol (&) is required on all applications that do not terminate immediately.
# Failure to provide them will cause Fluxbox not to start.

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
nitrogen --restore &
compton &
clipit &
nm-applet &
pulseaudio &
pa-applet &
cbatticon &
pamac-tray &
plank &
# sbxkb &   # keyboard layout switcher for the tray

# exec is for starting Fluxbox itself, do not put an ampersand (&) after this or Fluxbox will exit immediately.
# exec /usr/bin/fluxbox

# or if you want to keep a log, uncomment the below command and comment out the above command:
exec /usr/bin/fluxbox -log ~/.fluxbox/log