#!/usr/bin/env python

""" Prints dimensions of the active monitor """

def main():
    """ Using the active window print the dimensions of the monitor it is on """
    import gi
    gi.require_version('Gtk', '3.0')
    from gi.repository import Gtk

    try:
        active_window = Gtk.Window()
        screen = active_window.get_screen()
        active_monitor = screen.get_monitor_at_window(screen.get_active_window())
        monitor = screen.get_monitor_geometry(active_monitor)
        print("%s %s" % (monitor.width, monitor.height))
        return 0
    except:
        print("Not running under X")
        return 1


if __name__ == "__main__":
    main()
