#!/bin/sh

xdg=$(xdg-user-dir DESKTOP)
src='/usr/share/applications'

if [[ -f /usr/bin/thus ]];then
	install -Dm755 $src/thus.desktop \
	$xdg/thus.desktop
fi

if [[ -f /usr/bin/calamares ]];then
	install -Dm755 $src/calamares.desktop \
	$xdg/calamares.desktop
fi

if [[ -f /usr/bin/cli-installer ]];then
	install -Dm755 $src/cli-installer.desktop \
	$xdg/cli-installer.desktop
fi

if [[ -f "/usr/share/doc/livecd/Beginner_User_Guide.pdf" ]]; then
	ln -sf /usr/share/doc/livecd/Beginner_User_Guide.pdf \
	"$xdg/Beginner User Guide.pdf"
fi

if [[ -f "$src/manjaro-welcome.desktop" ]]; then
	install -Dm755 $src/manjaro-welcome.desktop \
	"$xdg/manjaro-welcome.desktop"
fi

if [[ -f "$src/hexchat.desktop" ]]; then
	install -Dm755 $src/hexchat.desktop \
	"$xdg/hexchat.desktop"
fi

# support sonar

if [[ -f "/usr/share/sonar/keyboard_shortcuts.txt" ]]; then
	ln -sf /usr/share/sonar/keyboard_shortcuts.txt \
	"$xdg/keyboard_shortcuts"
fi

if [[ -f "/usr/share/sonar/users_guide.odt" ]]; then
	ln -sf /usr/share/sonar/users_guide.odt \
	"$xdg/users_guide"
fi

if [[ -f "$src/ask_for_help_online.desktop" ]]; then
	install -Dm755 $src/ask_for_help_online.desktop \
	"$xdg/ask_for_help_online.desktop"
fi

if [[ -f "$src/connect_to_our_mumble_server_for_help.desktop" ]]; then
	install -Dm755 $src/connect_to_our_mumble_server_for_help.desktop \
	"$xdg/connect_to_our_mumble_server_for_help.desktop"
fi
