# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 215040);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 34);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1455655465576");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1455659065576");
user_pref("browser.search.countryCode", "IT");
user_pref("browser.search.region", "IT");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160211213400");
user_pref("browser.slowStartup.averageTime", 5190);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage", "https://manjaro.github.io");
user_pref("browser.startup.homepage_override.buildID", "20160211213400");
user_pref("browser.startup.homepage_override.mstone", "44.0.2");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1455741855970");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1455655519048");
user_pref("datareporting.policy.firstRunTime", "1455655455969");
user_pref("datareporting.sessions.current.activeTicks", 2);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 3603);
user_pref("datareporting.sessions.current.main", 267);
user_pref("datareporting.sessions.current.sessionRestored", 3391);
user_pref("datareporting.sessions.current.startTime", "1455655545200");
user_pref("datareporting.sessions.current.totalTime", 18);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.previous.0", "{\"s\":1455655451901,\"a\":15,\"t\":92,\"c\":true,\"m\":1431,\"fp\":7337,\"sr\":7153}");
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "%7B03cb16aa-4675-11e5-b233-213b1d5d46b0%7D:44.20160126");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "44.0.2");
user_pref("extensions.lastPlatformVersion", "44.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.experiment.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/theme");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.xpiState", "{\"app-global\":{\"{03cb16aa-4675-11e5-b233-213b1d5d46b0}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{03cb16aa-4675-11e5-b233-213b1d5d46b0}\",\"e\":true,\"v\":\"44.20160126\",\"st\":1455217848000,\"mt\":1455217847000},\"{52c2877e-44e1-11e5-8874-a62d1d5d46B0}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{52c2877e-44e1-11e5-8874-a62d1d5d46B0}\",\"e\":false,\"v\":\"44.20160126\",\"st\":1455217848000,\"mt\":1455217846000},\"{8a01dfcc-450f-11e5-909b-fb581d5d46b0}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{8a01dfcc-450f-11e5-909b-fb581d5d46b0}\",\"e\":false,\"v\":\"44.20160126\",\"st\":1455217848000,\"mt\":1455217847000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":false,\"v\":\"44.0.2\",\"st\":1455228322000,\"mt\":1455228322000}}}");
user_pref("gecko.buildID", "20160211213400");
user_pref("gecko.mstone", "44.0.2");
user_pref("general.skins.selectedSkin", "arc-dark-theme");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1455655521);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20160211213400");
user_pref("media.gmp-manager.lastCheck", 1455655520);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 9346);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("privacy.sanitize.migrateClearSavedPwdsOnExit", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1455655545);
user_pref("toolkit.telemetry.cachedClientID", "4fa118f7-6bd3-49ac-8d31-77bd0fcaede3");
user_pref("toolkit.telemetry.previousBuildID", "20160211213400");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
