#!/bin/bash

for i in $(gsettings list-schemas | grep cinnamon)
do
	gsettings reset-recursively $i
done

## reset gnome-terminal profile

# get profile id
default_profile=$(gsettings get org.gnome.Terminal.ProfilesList default)

# strip the quotes
profile=${default_profile:1:-1}

# reset values
gsettings reset-recursively "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$profile/"
