# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1421239681);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 13);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.search.defaultenginename", "Google");
user_pref("browser.search.selectedEngine", "Google");
user_pref("browser.slowStartup.averageTime", 3900);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20141127224750");
user_pref("browser.startup.homepage_override.mstone", "25.1.0");
user_pref("browser.startup.page", 0);
user_pref("browser.tabs.onTop", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:25.1.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/palemoon/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1421061856000,\"rdfTime\":1421061856000}}}]");
user_pref("extensions.lastAppVersion", "25.1.0");
user_pref("extensions.lastPlatformVersion", "25.1.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20141127224750");
user_pref("gecko.mstone", "25.1.0");
user_pref("intl.charsetmenu.browser.cache", "UTF-8, windows-1252");
user_pref("media.gstreamer.enabled", true);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 26147);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("status4evar.firstRun", false);
user_pref("status4evar.migration", 6);
user_pref("toolkit.startup.last_success", 1421239817);
user_pref("toolkit.telemetry.previousBuildID", "20141127224750");
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
