
Welcome to Sonar Linux !

To start the system enter 'start and press <return>


Available boot options:
start                    - Start Sonar Live System
nonfree                  - Start using also nVidia or Catalyst drivers
harddisk                 - Local boot from hard disk
memtest                  - Run Memory Test
hdt                      - Run Hardware Detection Tool
reboot                   - Reboot
poweroff                 - Power Off
