# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1453918215);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1453918335);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1454706873);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1453918095);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 307200);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.download.useDownloadDir", true);
user_pref("browser.migration.version", 13);
user_pref("browser.newtab.url", "about:newtab");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.preferences.advanced.selectedTabIndex", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.defaultenginename", "Startpage (SSL)");
user_pref("browser.search.selectedEngine", "Startpage (SSL)");
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.slowStartup.averageTime", 8330);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage", "http://www.fsf.org/");
user_pref("browser.startup.homepage_override.buildID", "20160201105311");
user_pref("browser.startup.homepage_override.mstone", "2.0.1");
user_pref("browser.syncPromoViewsLeftMap", "{\"bookmarks\":0}");
user_pref("browser.tabs.insertRelatedAfterCurrent", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:26.0.2");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/palemoon/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1454543233000,\"rdfTime\":1454518589000}}}]");
user_pref("extensions.lastAppVersion", "26.0.2");
user_pref("extensions.lastPlatformVersion", "2.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("font.name.serif.x-western", "Cantarell");
user_pref("font.size.variable.x-western", 17);
user_pref("gecko.buildID", "20151126081811");
user_pref("gecko.mstone", "25.8.1");
user_pref("general.autoScroll", true);
user_pref("goanna.buildID", "20160201105311");
user_pref("goanna.mstone", "2.0.1");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.importedState", true);
user_pref("privacy.cpd.offlineApps", true);
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("status4evar.firstRun", false);
user_pref("status4evar.migration", 6);
user_pref("toolkit.startup.last_success", 1454706749);
user_pref("xpinstall.whitelist.add", "");
