#!/usr/bin/env bash

# Manjaro Code Pipemenu
# written by Nathaniel Maia, December 2017

# Add something like this to your menu.xml
# <menu execute="manjaro-code-pipemenu" id="code" label="Code"/>

NAME="code"
PNAME="Code"
FAIL_MSG="No Apps Installed"

CMD=(atom brackets emacs geany gedit gvim leafpad mousepad vscode subl3)
DESC=(Atom Brackets Emacs Geany Gedit Gvim Leafpad Mousepad "Visual Studio" Sublime)

# source lib file
if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2>/dev/null; then
    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg"
    exit 1
fi

menu_Body() {
    for ((i=0; i<${#CMD[@]}; i++)); do
        if hash "${CMD[$i]}" &>/dev/null; then
            menuItem "${DESC[$i]}" "${CMD[$i]}"
        fi
    done
}

menuStart "$NAME" "$PNAME"
for x in "${CMD[@]}"; do
    if hash "$x" &>/dev/null; then
        num=1 ; break
    fi
done
if [[ $num -gt 0 ]]; then
    menu_Body
else
    menuSeparator "$FAIL_MSG"
    if hash pamac-manager &>/dev/null; then
        menuItem "Install with Package Manager" "pamac-manager"
    elif hash termite pacui &>/dev/null; then
        menuItem "Install with Package Manager" "termite -e pacui"
    fi
fi
menuEnd

exit 0
