#!/usr/bin/env bash

# A pipemenu base script/template for creating category based pipemenus
# written by Nathaniel Maia, December 2017 for Manjaro

# Add something like this to your menu.xml
# <menu execute="SCRIPTNAME" id="NAME" label="PNAME"/>

NAME="system"
PNAME="System"
FAIL_MSG="No Apps Installed"

CMD=(gparted nvidia-settings flash.sh etcher mintstick grub-customizer pacli pamac-manager
     thunar termite)
DESC=(Gparted Nvidia "Flash USB" Etcher Mintstick "Grub Customizer" "Package Manager" "Pamac Manager"
      "Root File Mananger" "Root Terminal")

if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2>/dev/null; then
    echo "[ERROR]: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg" ; exit 1
fi

menu_Body() {
    for ((i=0; i<${#CMD[@]}; i++)); do
        if hash "${CMD[$i]}" &>/dev/null; then
            if [[ "${CMD[$i]}" == 'pacli' ]]; then
                if hash termite &>/dev/null; then
                    menuItem "${DESC[$i]}" "termite -e ${CMD[$i]}"
                elif hash st &>/dev/null; then
                    menuItem "${DESC[$i]}" "st -e ${CMD[$i]}"
                elif hash urxvt &>/dev/null; then
                    menuItem "${DESC[$i]}" "urxvt -e ${CMD[$i]}"
                elif hash xterm &>/dev/null; then
                    menuItem "${DESC[$i]}" "xterm -e ${CMD[$i]}"
                fi
            elif [[ "${CMD[$i]}" == 'mintstick' ]]; then
                menuItem "${DESC[$i]} Format" "${CMD[$i]} -m format"
                menuItem "${DESC[$i]} Flash" "${CMD[$i]} -m iso"
            else
                menuItem "${DESC[$i]}" "gksudo ${CMD[$i]}"
            fi
        elif [[ "${CMD[$i]}" == etcher ]]; then
            if [[ -e /usr/share/applications/etcher-electron.desktop ]]; then
                menuItem "${DESC[$i]}" "/opt/Etcher/etcher-electron"
            fi
        fi
    done
}

menuStart "$NAME" "$PNAME"
for x in "${CMD[@]}"; do
    if hash "$x" &>/dev/null; then
        num=1 ; break
    fi
done
if [[ $num -gt 0 ]]; then
    menu_Body
else
    menuSeparator "$FAIL_MSG"
fi
menuEnd

exit 0
