# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1444599586);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1444599706);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1444599346);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1444599466);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 307200);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 13);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.search.defaultenginename", "Google");
user_pref("browser.search.selectedEngine", "Google");
user_pref("browser.slowStartup.averageTime", 9760);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage", "https://manjaro.github.io/");
user_pref("browser.startup.homepage_override.buildID", "20150923203929");
user_pref("browser.startup.homepage_override.mstone", "25.7.1");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:25.7.1");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/palemoon/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1443479628000,\"rdfTime\":1443453575000}}}]");
user_pref("extensions.lastAppVersion", "25.7.1");
user_pref("extensions.lastPlatformVersion", "25.7.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20150923203929");
user_pref("gecko.mstone", "25.7.1");
user_pref("intl.charsetmenu.browser.cache", "windows-1252, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 100636);
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("status4evar.firstRun", false);
user_pref("status4evar.migration", 6);
user_pref("toolkit.startup.last_success", 1444599844);
user_pref("xpinstall.whitelist.add", "");
