name: rebase

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/30 * * * *'
  
env:
  UPSTREAM_GIT: https://gitlab.manjaro.org/profiles-and-settings/desktop-settings.git

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
    - 
      name: checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PUSH_AND_TRIGGER }}
    - 
      name: add ssh pk
      if: ${{ contains(env.UPSTREAM_GIT, 'ssh') }}
      run: mkdir -p ~/.ssh/id_rsa && echo "${{ secrets.SSH_BASE64 }}" | base64 -d >~/.ssh/id_rsa
    - 
      name: check if behind upstream
      run: |
        git remote add upstream ${UPSTREAM_GIT}
        git fetch upstream
        git merge-base --is-ancestor $(git branch --show-current) upstream/$(git branch --show-current) && exit 1 || exit 0
    - 
      name: rebase
      if: ${{ failure() }}
      run: |
        git rebase
        git push --force-with-lease