name: rebase

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/30 * * * *'
  
env:
  UPSTREAM_GIT: https://gitlab.manjaro.org/profiles-and-settings/desktop-settings.git
  BASE_BRANCH: master

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
    - 
      name: checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PUSH_AND_TRIGGER }}
        fetch-depth: 0
    - 
      name: fetch upstream
      run: |
        git remote add upstream ${UPSTREAM_GIT}
        git fetch upstream
    - 
      name: rebase
      run: |
        git config user.email "info@jonas-strassel.de"
        git config user.name "Jonas Strassel"
        git pull --rebase upstream ${BASE_BRANCH}
        git push --force-with-lease
